title: Info Page
description: Info page for Jonathan Cothran developer
author: "Jonathan Cothran"

theme: minima

domain: jothdev.github.io  
url: https://jcothdev.github.io
baseurl: / 

# Minima social links
linkedin_username: jonathan-cothran-5bb514277
github_username: jcothdev

minima:
# Minima: custom header links
    header_pages:
        - docs/manifesto.md

include:
    - docs/
    - _layouts/

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
