title: Info Page
description: Info page for Jonathan Cothran developer
author: "Jonathan Cothran"

theme: minima

base_url: /

# Minima social links
linkedin_username: jonathan-cothran-5bb514277

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
#header_pages:
#  - _pages/frontpage.md
#  - _pages/about.md
#  - _pages/archive.md

# include:

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
